apiVersion: v1
kind: Namespace
metadata:
  name: httpbin3
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin3
  namespace: httpbin3
spec:
  type: ExternalName
  externalName: httpbin.org

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin3
  namespace: httpbin3
  annotations:
   cert-manager.io/cluster-issuer: lets-encrypt
   nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
   nginx.ingress.kubernetes.io/upstream-vhost: "httpbin.org"
spec:
  ingressClassName: public
  tls:
  - hosts:
    - httpbin3.klaud.online
    secretName: httpbin3-ingress-tls  
  rules:
  - host: httpbin3.klaud.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpbin3
            port:
              number: 443
---
