apiVersion: v1
kind: Namespace
metadata:
  name: ip
---
apiVersion: v1
kind: Service
metadata:
  name: ip
  namespace: ip
spec:
  type: ExternalName
  externalName: ip.iol.cz

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ip
  namespace: ip
  annotations:
   cert-manager.io/cluster-issuer: lets-encrypt
   nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
   nginx.ingress.kubernetes.io/upstream-vhost: "ip.iol.cz"
spec:
  ingressClassName: public
  tls:
  - hosts:
    - ip.klaud.online
    secretName: ip-ingress-tls  
  rules:
  - host: ip.klaud.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpbin3
            port:
              number: 80
---
