apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  #namespace: default
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80

# apiVersion: v1
# kind: Pod
# metadata:
#   name: myapp-pod
#   labels:
#     app: myapp
#     type: front-end
# spec:
#   containers: # list of containers
#     - name: nginx-container
#       image: nginx #docker image

